//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScadaHisAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalogSummaryHistory
    {
        public string TagName { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public Nullable<int> OPCQuality { get; set; }
        public Nullable<double> PercentGood { get; set; }
        public Nullable<double> First { get; set; }
        public Nullable<System.DateTime> FirstDateTime { get; set; }
        public Nullable<double> Last { get; set; }
        public Nullable<System.DateTime> LastDateTime { get; set; }
        public Nullable<double> Minimum { get; set; }
        public Nullable<System.DateTime> MinDateTime { get; set; }
        public Nullable<double> Maximum { get; set; }
        public Nullable<System.DateTime> MaxDateTime { get; set; }
        public Nullable<double> Average { get; set; }
        public Nullable<double> StdDev { get; set; }
        public Nullable<double> Integral { get; set; }
        public Nullable<int> ValueCount { get; set; }
        public string SourceTag { get; set; }
        public string SourceServer { get; set; }
        public Nullable<int> wwCycleCount { get; set; }
        public Nullable<int> wwResolution { get; set; }
        public string wwTimeZone { get; set; }
        public string wwVersion { get; set; }
        public int wwTagKey { get; set; }
        public string wwRetrievalMode { get; set; }
    }
}
